# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    timezone: 'Asia/Jakarta'
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            viewer: false
            ignored_columns:
                - createdAt
                - deletedAt
                - updatedAt
