# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_USER
    versioning: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    service:
        serializer: ~
    serializer:
        groups: ['read']
    view:
        view_response_listener: 'force'
        formats:
            json: true
