# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    versioning: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

    view:
        view_response_listener: 'force'
        formats:
            json: true
