framework:
    trusted_proxies: '192.0.0.1,172.0.0.0/8,10.0.0.0/8'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port' ]
    translator:
        enabled: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    http_cache: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        cookie_lifetime: 3600
        enabled: true
        use_cookies: true
        handler_id: snc_redis.session.handler

    #esi: true
    #fragments: true
    php_errors:
        log: true
