swoole:
    http_server:
        port: 9501
        host: 0.0.0.0
        running_mode: process
        socket_type: tcp
        ssl_enabled: false
        static: advanced
        hmr: inotify
        services:
            session_cookie_event_listener: true
