framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: failed
                retry_strategy:
                    max_retries: 3
                    delay: 5000
                    multiplier: 2
                    max_delay: 0
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    table_name: 'core_messages'
            sync: 'sync://'
        routing:
            KejawenLab\ApiSkeleton\Entity\Message\EntityPersisted: sync
            KejawenLab\ApiSkeleton\Entity\Message\EntityRemoved: async
