nelmio_api_doc:
    documentation:
        info:
            title: '%env(resolve:APP_TITLE)%'
            description: '%env(resolve:APP_DESCRIPTION)%'
            version: '%env(resolve:APP_VERSION)%'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!(doc)$)
