nelmio_api_doc:
    documentation:
        info:
            title: '%env(resolve:APP_TITLE)%'
            description: '%env(resolve:APP_DESCRIPTION)%'
            version: '%env(resolve:APP_VERSION)%'
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {JWT_TOKEN}'
                name: Authorization
                in: header
    areas: # to filter documented areas
        path_patterns:
            - ^/api/(?!(doc)$)
