twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        title: '%env(resolve:APP_TITLE)%'
        app_title: '%env(resolve:APP_TITLE)%'
        app_description: '%env(resolve:APP_DESCRIPTION)%'
        version: '%env(resolve:APP_VERSION)%'
