vich_uploader:
    db_driver: orm
    storage: '@KejawenLab\ApiSkeleton\Media\Storage'
    mappings:
        media:
            uri_prefix: /medias
            upload_destination: '%env(resolve:APP_UPLOAD_DIR)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
