vich_uploader:
    db_driver: orm
    storage: '@Alpabit\ApiSkeleton\Media\Storage'
    mappings:
        media:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/storage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
