version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
          - .env
        volumes:
            - .:/semart
        links:
            - session
            - db
        depends_on:
            - session

    balancer:
        image: dockercloud/haproxy:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9876:80
        links:
            - app
        depends_on:
            - app

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: semart

    adminer:
        image: adminer:latest
        ports:
            - 6789:8080
        links:
            - db

    session:
        image: redis:alpine
