#!/bin/bash

GREEN="\033[0;32m"
RESET="\0033[0m"

echo -e "{$GREEN}Installing Docker${RESET}"
sudo apt remove --yes docker docker-engine docker.io containerd runc
sudo apt update
sudo apt --yes --no-install-recommends install apt-transport-https ca-certificates
wget --quiet --output-document=- https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release --codename --short) stable"
sudo apt update
sudo apt --yes --no-install-recommends install docker-ce docker-ce-cli containerd.io
sudo usermod --append --groups docker "$USER"
sudo systemctl enable docker

echo -e "{$GREEN}Docker installed successfully${RESET}"

echo -e "{$GREEN}Starting Docker${RESET}"
sleep 5
echo -e "{$GREEN}Docker started${RESET}"

echo -e "{$GREEN}Installing Docker Compose${RESET}"
sudo wget --output-document=/usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.26.0/run.sh
sudo chmod +x /usr/local/bin/docker-compose
sudo wget --output-document=/etc/bash_completion.d/docker-compose "https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose"
echo -e "{$GREEN}Docker Compose installed successfully${RESET}"

echo -e "{$GREEN}Please relogin to make sure all changes applied${RESET}"
