semart_api:
    prefix: /api
    resource: ../../lib/Controller/
    type: annotation

semart_admin:
    prefix: /admin
    resource: ../../lib/Admin/Controller/
    type: annotation

app_api:
    prefix: /api
    resource: ../../app/Controller/
    type: annotation

app_admin:
    prefix: /admin
    resource: ../../app/Admin/Controller/
    type: annotation

admin_logout:
    path: /admin/logout

kernel:
    resource: ../../lib/Kernel.php
    type: annotation
