Cron\CronBundle\Entity\CronJob:
    attributes:
        id:
            groups: ['read']
        name:
            groups: ['read']
        description:
            groups: ['read']
        command:
            groups: ['read']
        schedule:
            groups: ['read']
        enabled:
            groups: ['read']
Cron\CronBundle\Entity\CronReport:
    attributes:
        id:
            groups: ['read']
        runAt:
            groups: ['read']
        runTime:
            groups: ['read']
        exitCode:
            groups: ['read']
        output:
            groups: ['read']
