monolog:
    channels: [db, audit, cron]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        db:
            type: stream
            path: "%kernel.logs_dir%/db.log"
            level: debug
            channels: [db]
        audit:
            type: stream
            path: "%kernel.logs_dir%/audit.log"
            level: debug
            channels: [audit]
        cron:
            type: stream
            path: "%kernel.logs_dir%/cron.log"
            level: debug
            channels: [cron]
