Cron\CronBundle\Entity\CronJob:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 191
        description:
            - NotBlank: ~
            - Length:
                min: 3
                max: 191
        command:
            - NotBlank: ~
            - KejawenLab\Semart\ApiSkeleton\Cron\Validator\ConsoleCommand: ~
        schedule:
            - NotBlank: ~
            - KejawenLab\Semart\ApiSkeleton\Cron\Validator\CronScheduleFormat: ~
        enabled:
            - NotBlank: ~
