home:
    path: /
    methods: [GET]
    controller: KejawenLab\ApiSkeleton\Controller\HomeController::__invoke
api:
    path: /api
    methods: [GET]
    controller: KejawenLab\ApiSkeleton\Controller\HomeController::__invoke
health:
    path: /health
    methods: [ GET ]
    controller: KejawenLab\ApiSkeleton\Controller\HealthController::__invoke
