home:
    path: /
    methods: [GET]
    controller: KejawenLab\ApiSkeleton\Controller\HomeController::__invoke
api:
    path: /api
    methods: [GET]
    controller: KejawenLab\ApiSkeleton\Controller\HomeController::__invoke
